title: Moabiter Lastenlaufrad Kiez-WM 2026
description: Die erste Moabiter Lastenlaufrad Kiez-Weltmeisterschaft – 9. Mai 2026
baseurl: ""
url: "https://moabit.pimpmycargo.bike"
lang: de

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

include:
  - assets/kiez-wm-2026.ics

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
